---
title: "Opsin Gene Adjacency Explore"
output: html_document
date: "2026-01-26"
---

```{r}
# load required libraries
#Note you only need to install packages once then you can comment it out
install.packages("dplyr")
library(dplyr)
library(readr)
library(tidyverse)

# Read in the data and store as "Opsin_AEP_adjacency" data object
Opsin_AEP_adjacency <- read_csv("Opsin_gene_adjacency - Sheet1.csv")

# display the first 6 rows
head(Opsin_AEP_adjacency)
```

```{r}
# Using dplyr to find duplicate values
Opsin_AEP_adjacency%>% 
  rename(
    distance_h_bp = distance_h_id,
    distance_i_bp = distance_i_id)

colnames(Opsin_AEP_adjacency
         )

```

```{r}
Opsin_AEP_adjacency.NAX <- Opsin_AEP_adjacency %>% 
  select(where(~ !all(is.na(.x))))
colnames(Opsin_AEP_adjacency.NAX)

```

```{r}
#Pull the rows with the duplicated values into a new table
library(rbenchmark)
library(dplyr)
library(data.table)

#create a data.frame
df<-data.frame(
Gene_a_id = rep(c("HVAEP1.G000061,HVAEP1.G001381,HVAEP1.G002053"),each=50),
Gene_a_type= sample(PREDICTED: dymeclin-like [Hydra vulgaris],PREDICTED: parapinopsin-like [Hydra vulgaris]v,replace=TRUE)
)
duplicated_rows_base<-duplicated.data.frame(Logic)






